### ISSUE TITLE
Events not working

### ISSUE THREAD

**Issue by VoIcanis** [Blackvein/Quests#138]
I tried to give items or perform commands using event of finish stage and the message comes through but no item or command, there is no error in the console where should i start in debugging this?

**EDIT**: I made a quest just for this post: This is with 2.5.1-b86

```
  custom8:
    name: TEST Dont Use
    npc-giver-id: 1
    redo-delay: 5
    ask-message: Starting Test
    finish-message: Ending Test
    stages:
      ordered:
        '1':
          start-event: TheBow
          finish-event: TheBow
        '2':
          npc-ids-to-talk-to:
          - 1
          complete-message: Testing done
```

**This is the Event below**

```
  TheBow:
    items:
    - name-BOW:amount-1:displayname-Alozars Bow
```

in this particular test you recieve the bow on start event but you never recieve one on finish event also you cannot speak to the npc so you never get complete-message: Testing done

and as before still no error message

**EDIT 2**: ok so i edited the quest and made you have to kill 1 pig, after killing the pig you can go talk to the npc to end it all but finish event still does not fire the finish-event.

**EDIT 3**: Here is the original quest after i tried to change giving the bow to the start-event instead:

``````
  custom4:
    name: The Bow
    npc-giver-id: 1
    redo-delay: 5000
    ask-message: I need a §bBow§r, Would you mind getting me one from Elkom? He lives in the house across the bridge.
    finish-message: Now if i could just find some arrows...
    stages:
      ordered:
        '1':
          npc-ids-to-talk-to:
          - 2
          complete-message: I ran out of String if you get me some I can make the &bBow&r for you!
        '2':
          items-to-deliver:
          - name-STRING:amount-3
          npc-delivery-ids:
          - 2
          delivery-messages:
          - Thank you for the String
          complete-message: Here is Alozars §bBow§r please return it to him.
        '3':
          items-to-deliver:
          - name-BOW:amount-1:displayname-Alozars Bow
          npc-delivery-ids:
          - 1
          delivery-messages:
          - Thank you for me Bow!
          start-event: TheBow
    rewards:
      money: 500
      quest-points: 1
      exp: 100
```.
that edit works since i changed it to start event, but you never see the bow

if you use this as the stages you still never see the bow in your inventory
``````

```
    '1':
      npc-ids-to-talk-to:
      - 2
      complete-message: I ran out of String if you get me some I can make the &bBow&r for you!
    '2':
      items-to-deliver:
      - name-STRING:amount-3
      npc-delivery-ids:
      - 2
      delivery-messages:
      - Thank you for the String
      complete-message: It may take me some time to make the Bow please come back soon.
    '3':
      npc-ids-to-talk-to:
      - 2
      start-event: TheBow
      complete-message: Here is Alozars &bBow&r, please return it to him.
```

```
```
