### ISSUE TITLE
Can't complete quests

### ISSUE THREAD

**Issue by Poweringg** [Blackvein/Quests#407]
hello, i created a quest, and when i tryied to complete it, i cant, i didn't get my rewards etc..
Here is my "Quests.yml"

```
quests:
  Miner:
    name: Stone Miner
    ask-message: <yellow>Could you mine <purple>10<yellow> blocks of <purple>Stone<yellow>, and deliver the <purple>10<yellow> pieces <yellow>of <purple>Cobblestone<yellow> to me?
    finish-message: <yellow>Well done. Here is your reward.
    redo-delay: 1800
    requirements:
      items:
      - name-wood_pickaxe:amount-1
      remove-items:
      - false
      fail-requirement-message: <red>You must have a <purple>Wooden Pickaxe<red> first.
    stages:
      ordered:
        '1':
          break-block-names:
          - stone
          break-block-amounts:
          - 10
    rewards:
      money: 1000
      quest-points: 1
  Hunter:
    name: Mob Hunter
    ask-message: <yellow>Kill an assortment of Mobs.
    finish-message: <yellow>Excellent. Here is a <purple>Diamond Sword<yellow>.
    requirements:
      quests:
      - Stone Miner
      fail-requirement-message: <red>Complete <purple>Stone Miner<red> first.
    stages:
      ordered:
        '1':
          death-event: DeathFail
          mobs-to-kill:
          - Pig
          mob-amounts:
          - 3
          finish-event: GoodJob
        '2':
          death-event: DeathFail
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 2
          finish-event: GoodJob
        '3':
          death-event: DeathFail
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 1
    rewards:
      items:
      - name-diamond_sword:amount-1
      exp: 100
      quest-points: 1
  CatchFish:
    name: Catch Fish
    ask-message: <yellow>Catch some fish!
    finish-message: <yellow>Excellent. Here is some <green>experience<yellow>.
    requirements:
      quests:
      - Stone Miner
      fail-requirement-message: <red>Complete <purple>Stone Miner<red> first.
    stages:
      ordered:
        '1':
          start-event: FishingStart
          death-event: DeathFail
          chat-events:
          - RodEvent
          chat-event-triggers:
          - rod
          fish-to-catch: 5
    rewards:
      exp: 250
  custom1:
    name: Tutorial
    npc-giver-id: 125
    ask-message: Welcome!
    finish-message: Quest completed
    gui-display: name-GRASS:amount-1
    stages:
      ordered:
        '1':
          npc-ids-to-talk-to:
          - 123
    rewards:
      mcmmo-skills:
      - Unarmed
      mcmmo-levels:
      - 1

```

What should I do? Many thanks!
