### ISSUE TITLE
Place event with chest block

### ISSUE THREAD

**Issue by Vynderman** [Blackvein/Quests#432]
If I using chest as question target (like place chest) then I cannot complete quest (quest does not count). It is doesnt works with wood(en)_door too. No errors in console. It seems like chest isnt chest :)

Piece of config:

```
          place-block-names:
          - chest
          - wooden_door (Also tried wood_door)
          place-block-amounts:
          - 1
          - 1
          place-block-durability:
          - 0
          - 0
```

Spigot 1.9.4 R01. Quests latest version (From Jenkins, 2.7.3. 117 commit).
