### ISSUE TITLE
BreakBlock duplicating datas

### ISSUE THREAD

**Issue by monnierant** [Blackvein/Quests#434]
When a player log of and log in on the server after taking the quest it appear to duplicate breaking datas.

Here is the quest stage

```
          break-block-names:
          - stone
          break-block-amounts:
          - 1500
          break-block-durability:
          - 0
```

And here is what we see in the data file after some reconection

```

  jobs_mineur_missions_01:
    blocks-broken-names:
    - STONE
    - STONE
    - STONE
    blocks-broken-amounts:
    - 0
    - 0
    - 5
    blocks-broken-durability:
    - 0
    - 0
    - 0  
```
