### ISSUE TITLE
Error when you restart the plugin after creating the quest

### ISSUE THREAD

**Issue by MrSmile31** [Blackvein/Quests#483]
Error:
@`10.02 19:01:59 [Server] INFO MrSmile31 issued server command: /questsadmin reload
10.02 19:01:59 [Server] ERROR null
10.02 19:01:59 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'questsadmin' in plugin Quests v2.7.6-b120
10.02 19:01:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
10.02 19:01:59 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
10.02 19:01:59 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
10.02 19:01:59 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
10.02 19:01:59 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_92]
10.02 19:01:59 [Server] INFO at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_92]
10.02 19:01:59 [Server] INFO at me.blackvein.quests.Quests.processStages(Quests.java:3520) ~[?:?]
10.02 19:01:59 [Server] INFO at me.blackvein.quests.Quests.loadQuests(Quests.java:2904) ~[?:?]
10.02 19:01:59 [Server] INFO at me.blackvein.quests.Quests.reloadQuests(Quests.java:2662) ~[?:?]
10.02 19:01:59 [Server] INFO at me.blackvein.quests.Quests.adminReload(Quests.java:884) ~[?:?]
10.02 19:01:59 [Server] INFO at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:807) ~[?:?]
10.02 19:01:59 [Server] INFO at me.blackvein.quests.Quests.onCommand(Quests.java:788) ~[?:?]
10.02 19:01:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:01:59 [Server] INFO ... 15 more
10.02 19:02:04 [Multicraft] Skipped 5 lines due to rate limit (30/s)
10.02 19:02:04 [Server] INFO MrSmile31 issued server command: /questsadmin reload
10.02 19:02:04 [Server] ERROR null
10.02 19:02:04 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'questsadmin' in plugin Quests v2.7.6-b120
10.02 19:02:04 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:02:04 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:02:04 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:02:04 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:02:04 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:02:04 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:02:04 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:02:04 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:02:04 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
10.02 19:02:04 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
10.02 19:02:04 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:02:04 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:02:04 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:02:04 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:02:04 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [myj8.jar:git-Spigot-7d78b81-7e19325]
10.02 19:02:04 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
10.02 19:02:04 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
10.02 19:02:04 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_92]
10.02 19:02:04 [Server] INFO at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_92]
10.02 19:02:04 [Server] INFO at me.blackvein.quests.Quests.processStages(Quests.java:3520) ~[?:?]
10.02 19:02:04 [Server] INFO at me.blackvein.quests.Quests.loadQuests(Quests.java:2904) ~[?:?]
10.02 19:02:04 [Server] INFO at me.blackvein.quests.Quests.reloadQuests(Quests.java:2662) ~[?:?]
10.02 19:02:04 [Server] INFO at me.blackvein.quests.Quests.adminReload(Quests.java:884) ~[?:?]
10.02 19:02:04 [Server] INFO at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:807) ~[?:?]
10.02 19:02:04 [Server] INFO at me.blackvein.quests.Quests.onCommand(Quests.java:788) ~[?:?]
10.02 19:02:04 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[myj8.jar:git-Spigot-7d78b81-7e19325]`

quests.yml:
```
@  custom6:
    name: Help
    npc-giver-id: 23
    redo-delay: 10000
    ask-message: #rus text)
    finish-message: #rus text)
    gui-display: name-LOG:amount-1
    stages:
      ordered:
        '1':
          break-block-names:
          - log
          break-block-amounts:
          - 32
          break-block-durability: []
          start-message: #rus text)
        '2':
          break-block-names:
          - '82'
          break-block-amounts:
          - 32
          start-message: rus text)
        '3':
          items-to-deliver:
          - name-LOG:amount-32
          npc-delivery-ids:
          - 23
          delivery-messages:
          - #rus text)
          start-message: rus text)
        '4':
          items-to-deliver:
          - name-CLAY_BALL:amount-32
          npc-delivery-ids:
          - 23
          delivery-messages:
          - #rus text)
          start-message: #rus text)
```
